//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Deneme_11.IdeaV2WBS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IdeaV2Soap", Namespace="http://tempuri.org/")]
    public partial class IdeaV2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GirisKontrolOperationCompleted;
        
        private System.Threading.SendOrPostCallback DuzenleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciDurumListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciDurumuKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdresTipiListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdresTipiKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback TelefonListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TelefonKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback TelefonTipiListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TelefonTipiKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlceListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback IlceKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback KanGruplariListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KanGruplariKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback RolListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UstKullaniciListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiTelefonlariGetirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IdeaV2() {
            this.Url = global::Deneme_11.Properties.Settings.Default.Deneme_11_IdeaV2WBS_IdeaV2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GirisKontrolCompletedEventHandler GirisKontrolCompleted;
        
        /// <remarks/>
        public event DuzenleCompletedEventHandler DuzenleCompleted;
        
        /// <remarks/>
        public event IlListesiCompletedEventHandler IlListesiCompleted;
        
        /// <remarks/>
        public event KullaniciDurumListesiCompletedEventHandler KullaniciDurumListesiCompleted;
        
        /// <remarks/>
        public event KullaniciDurumuKaydetCompletedEventHandler KullaniciDurumuKaydetCompleted;
        
        /// <remarks/>
        public event AdresTipiListesiCompletedEventHandler AdresTipiListesiCompleted;
        
        /// <remarks/>
        public event AdresTipiKaydetCompletedEventHandler AdresTipiKaydetCompleted;
        
        /// <remarks/>
        public event IlKaydetCompletedEventHandler IlKaydetCompleted;
        
        /// <remarks/>
        public event TelefonListesiCompletedEventHandler TelefonListesiCompleted;
        
        /// <remarks/>
        public event TelefonKaydetCompletedEventHandler TelefonKaydetCompleted;
        
        /// <remarks/>
        public event TelefonTipiListesiCompletedEventHandler TelefonTipiListesiCompleted;
        
        /// <remarks/>
        public event TelefonTipiKaydetCompletedEventHandler TelefonTipiKaydetCompleted;
        
        /// <remarks/>
        public event IlceListesiCompletedEventHandler IlceListesiCompleted;
        
        /// <remarks/>
        public event IlceKaydetCompletedEventHandler IlceKaydetCompleted;
        
        /// <remarks/>
        public event KanGruplariListesiCompletedEventHandler KanGruplariListesiCompleted;
        
        /// <remarks/>
        public event KanGruplariKaydetCompletedEventHandler KanGruplariKaydetCompleted;
        
        /// <remarks/>
        public event KullaniciListesiCompletedEventHandler KullaniciListesiCompleted;
        
        /// <remarks/>
        public event KullaniciKaydetCompletedEventHandler KullaniciKaydetCompleted;
        
        /// <remarks/>
        public event RolListesiCompletedEventHandler RolListesiCompleted;
        
        /// <remarks/>
        public event KisiListesiCompletedEventHandler KisiListesiCompleted;
        
        /// <remarks/>
        public event UstKullaniciListesiCompletedEventHandler UstKullaniciListesiCompleted;
        
        /// <remarks/>
        public event KisiKaydetCompletedEventHandler KisiKaydetCompleted;
        
        /// <remarks/>
        public event KisiTelefonlariGetirCompletedEventHandler KisiTelefonlariGetirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GirisKontrol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sonuc")]
        public bool GirisKontrol(string email, string sifre, string versiyon, out string aciklama, out int kullanici_id, out int rol_id, out int ustkullaniciid, out string adsoyad) {
            object[] results = this.Invoke("GirisKontrol", new object[] {
                        email,
                        sifre,
                        versiyon});
            aciklama = ((string)(results[1]));
            kullanici_id = ((int)(results[2]));
            rol_id = ((int)(results[3]));
            ustkullaniciid = ((int)(results[4]));
            adsoyad = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GirisKontrolAsync(string email, string sifre, string versiyon) {
            this.GirisKontrolAsync(email, sifre, versiyon, null);
        }
        
        /// <remarks/>
        public void GirisKontrolAsync(string email, string sifre, string versiyon, object userState) {
            if ((this.GirisKontrolOperationCompleted == null)) {
                this.GirisKontrolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGirisKontrolOperationCompleted);
            }
            this.InvokeAsync("GirisKontrol", new object[] {
                        email,
                        sifre,
                        versiyon}, this.GirisKontrolOperationCompleted, userState);
        }
        
        private void OnGirisKontrolOperationCompleted(object arg) {
            if ((this.GirisKontrolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GirisKontrolCompleted(this, new GirisKontrolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Duzenle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Duzenle(int kullaniciid, string email, string sifre, string adisoyadi) {
            this.Invoke("Duzenle", new object[] {
                        kullaniciid,
                        email,
                        sifre,
                        adisoyadi});
        }
        
        /// <remarks/>
        public void DuzenleAsync(int kullaniciid, string email, string sifre, string adisoyadi) {
            this.DuzenleAsync(kullaniciid, email, sifre, adisoyadi, null);
        }
        
        /// <remarks/>
        public void DuzenleAsync(int kullaniciid, string email, string sifre, string adisoyadi, object userState) {
            if ((this.DuzenleOperationCompleted == null)) {
                this.DuzenleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDuzenleOperationCompleted);
            }
            this.InvokeAsync("Duzenle", new object[] {
                        kullaniciid,
                        email,
                        sifre,
                        adisoyadi}, this.DuzenleOperationCompleted, userState);
        }
        
        private void OnDuzenleOperationCompleted(object arg) {
            if ((this.DuzenleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DuzenleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IlListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet IlListesi() {
            object[] results = this.Invoke("IlListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void IlListesiAsync() {
            this.IlListesiAsync(null);
        }
        
        /// <remarks/>
        public void IlListesiAsync(object userState) {
            if ((this.IlListesiOperationCompleted == null)) {
                this.IlListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlListesiOperationCompleted);
            }
            this.InvokeAsync("IlListesi", new object[0], this.IlListesiOperationCompleted, userState);
        }
        
        private void OnIlListesiOperationCompleted(object arg) {
            if ((this.IlListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlListesiCompleted(this, new IlListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KullaniciDurumListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KullaniciDurumListesi() {
            object[] results = this.Invoke("KullaniciDurumListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciDurumListesiAsync() {
            this.KullaniciDurumListesiAsync(null);
        }
        
        /// <remarks/>
        public void KullaniciDurumListesiAsync(object userState) {
            if ((this.KullaniciDurumListesiOperationCompleted == null)) {
                this.KullaniciDurumListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciDurumListesiOperationCompleted);
            }
            this.InvokeAsync("KullaniciDurumListesi", new object[0], this.KullaniciDurumListesiOperationCompleted, userState);
        }
        
        private void OnKullaniciDurumListesiOperationCompleted(object arg) {
            if ((this.KullaniciDurumListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciDurumListesiCompleted(this, new KullaniciDurumListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KullaniciDurumuKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KullaniciDurumuKaydet(string durumadi, int durumid, int updated) {
            this.Invoke("KullaniciDurumuKaydet", new object[] {
                        durumadi,
                        durumid,
                        updated});
        }
        
        /// <remarks/>
        public void KullaniciDurumuKaydetAsync(string durumadi, int durumid, int updated) {
            this.KullaniciDurumuKaydetAsync(durumadi, durumid, updated, null);
        }
        
        /// <remarks/>
        public void KullaniciDurumuKaydetAsync(string durumadi, int durumid, int updated, object userState) {
            if ((this.KullaniciDurumuKaydetOperationCompleted == null)) {
                this.KullaniciDurumuKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciDurumuKaydetOperationCompleted);
            }
            this.InvokeAsync("KullaniciDurumuKaydet", new object[] {
                        durumadi,
                        durumid,
                        updated}, this.KullaniciDurumuKaydetOperationCompleted, userState);
        }
        
        private void OnKullaniciDurumuKaydetOperationCompleted(object arg) {
            if ((this.KullaniciDurumuKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciDurumuKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdresTipiListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AdresTipiListesi() {
            object[] results = this.Invoke("AdresTipiListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AdresTipiListesiAsync() {
            this.AdresTipiListesiAsync(null);
        }
        
        /// <remarks/>
        public void AdresTipiListesiAsync(object userState) {
            if ((this.AdresTipiListesiOperationCompleted == null)) {
                this.AdresTipiListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdresTipiListesiOperationCompleted);
            }
            this.InvokeAsync("AdresTipiListesi", new object[0], this.AdresTipiListesiOperationCompleted, userState);
        }
        
        private void OnAdresTipiListesiOperationCompleted(object arg) {
            if ((this.AdresTipiListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdresTipiListesiCompleted(this, new AdresTipiListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AdresTipiKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdresTipiKaydet(string adrestipiadi, int adrestipiid, int updated) {
            this.Invoke("AdresTipiKaydet", new object[] {
                        adrestipiadi,
                        adrestipiid,
                        updated});
        }
        
        /// <remarks/>
        public void AdresTipiKaydetAsync(string adrestipiadi, int adrestipiid, int updated) {
            this.AdresTipiKaydetAsync(adrestipiadi, adrestipiid, updated, null);
        }
        
        /// <remarks/>
        public void AdresTipiKaydetAsync(string adrestipiadi, int adrestipiid, int updated, object userState) {
            if ((this.AdresTipiKaydetOperationCompleted == null)) {
                this.AdresTipiKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdresTipiKaydetOperationCompleted);
            }
            this.InvokeAsync("AdresTipiKaydet", new object[] {
                        adrestipiadi,
                        adrestipiid,
                        updated}, this.AdresTipiKaydetOperationCompleted, userState);
        }
        
        private void OnAdresTipiKaydetOperationCompleted(object arg) {
            if ((this.AdresTipiKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdresTipiKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IlKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("yeni_id")]
        public int IlKaydet(string iladi, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> ilid, int updated) {
            object[] results = this.Invoke("IlKaydet", new object[] {
                        iladi,
                        ilid,
                        updated});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IlKaydetAsync(string iladi, System.Nullable<int> ilid, int updated) {
            this.IlKaydetAsync(iladi, ilid, updated, null);
        }
        
        /// <remarks/>
        public void IlKaydetAsync(string iladi, System.Nullable<int> ilid, int updated, object userState) {
            if ((this.IlKaydetOperationCompleted == null)) {
                this.IlKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlKaydetOperationCompleted);
            }
            this.InvokeAsync("IlKaydet", new object[] {
                        iladi,
                        ilid,
                        updated}, this.IlKaydetOperationCompleted, userState);
        }
        
        private void OnIlKaydetOperationCompleted(object arg) {
            if ((this.IlKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlKaydetCompleted(this, new IlKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelefonListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TelefonListesi() {
            object[] results = this.Invoke("TelefonListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TelefonListesiAsync() {
            this.TelefonListesiAsync(null);
        }
        
        /// <remarks/>
        public void TelefonListesiAsync(object userState) {
            if ((this.TelefonListesiOperationCompleted == null)) {
                this.TelefonListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelefonListesiOperationCompleted);
            }
            this.InvokeAsync("TelefonListesi", new object[0], this.TelefonListesiOperationCompleted, userState);
        }
        
        private void OnTelefonListesiOperationCompleted(object arg) {
            if ((this.TelefonListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TelefonListesiCompleted(this, new TelefonListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelefonKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TelefonKaydet(int TelefonId, int TelefonNo, int TelefonTipiId, int KisiId, int KullaniciId, int Updated) {
            this.Invoke("TelefonKaydet", new object[] {
                        TelefonId,
                        TelefonNo,
                        TelefonTipiId,
                        KisiId,
                        KullaniciId,
                        Updated});
        }
        
        /// <remarks/>
        public void TelefonKaydetAsync(int TelefonId, int TelefonNo, int TelefonTipiId, int KisiId, int KullaniciId, int Updated) {
            this.TelefonKaydetAsync(TelefonId, TelefonNo, TelefonTipiId, KisiId, KullaniciId, Updated, null);
        }
        
        /// <remarks/>
        public void TelefonKaydetAsync(int TelefonId, int TelefonNo, int TelefonTipiId, int KisiId, int KullaniciId, int Updated, object userState) {
            if ((this.TelefonKaydetOperationCompleted == null)) {
                this.TelefonKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelefonKaydetOperationCompleted);
            }
            this.InvokeAsync("TelefonKaydet", new object[] {
                        TelefonId,
                        TelefonNo,
                        TelefonTipiId,
                        KisiId,
                        KullaniciId,
                        Updated}, this.TelefonKaydetOperationCompleted, userState);
        }
        
        private void OnTelefonKaydetOperationCompleted(object arg) {
            if ((this.TelefonKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TelefonKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelefonTipiListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet TelefonTipiListesi() {
            object[] results = this.Invoke("TelefonTipiListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void TelefonTipiListesiAsync() {
            this.TelefonTipiListesiAsync(null);
        }
        
        /// <remarks/>
        public void TelefonTipiListesiAsync(object userState) {
            if ((this.TelefonTipiListesiOperationCompleted == null)) {
                this.TelefonTipiListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelefonTipiListesiOperationCompleted);
            }
            this.InvokeAsync("TelefonTipiListesi", new object[0], this.TelefonTipiListesiOperationCompleted, userState);
        }
        
        private void OnTelefonTipiListesiOperationCompleted(object arg) {
            if ((this.TelefonTipiListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TelefonTipiListesiCompleted(this, new TelefonTipiListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TelefonTipiKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void TelefonTipiKaydet(string TelefonTipiAdi, int TelefonTipiId, int Updated) {
            this.Invoke("TelefonTipiKaydet", new object[] {
                        TelefonTipiAdi,
                        TelefonTipiId,
                        Updated});
        }
        
        /// <remarks/>
        public void TelefonTipiKaydetAsync(string TelefonTipiAdi, int TelefonTipiId, int Updated) {
            this.TelefonTipiKaydetAsync(TelefonTipiAdi, TelefonTipiId, Updated, null);
        }
        
        /// <remarks/>
        public void TelefonTipiKaydetAsync(string TelefonTipiAdi, int TelefonTipiId, int Updated, object userState) {
            if ((this.TelefonTipiKaydetOperationCompleted == null)) {
                this.TelefonTipiKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTelefonTipiKaydetOperationCompleted);
            }
            this.InvokeAsync("TelefonTipiKaydet", new object[] {
                        TelefonTipiAdi,
                        TelefonTipiId,
                        Updated}, this.TelefonTipiKaydetOperationCompleted, userState);
        }
        
        private void OnTelefonTipiKaydetOperationCompleted(object arg) {
            if ((this.TelefonTipiKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TelefonTipiKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IlceListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet IlceListesi(int ilid) {
            object[] results = this.Invoke("IlceListesi", new object[] {
                        ilid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void IlceListesiAsync(int ilid) {
            this.IlceListesiAsync(ilid, null);
        }
        
        /// <remarks/>
        public void IlceListesiAsync(int ilid, object userState) {
            if ((this.IlceListesiOperationCompleted == null)) {
                this.IlceListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlceListesiOperationCompleted);
            }
            this.InvokeAsync("IlceListesi", new object[] {
                        ilid}, this.IlceListesiOperationCompleted, userState);
        }
        
        private void OnIlceListesiOperationCompleted(object arg) {
            if ((this.IlceListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlceListesiCompleted(this, new IlceListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IlceKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("yeni_id")]
        public int IlceKaydet(string ilce_ad, int updated, int ilce_id, int il_id) {
            object[] results = this.Invoke("IlceKaydet", new object[] {
                        ilce_ad,
                        updated,
                        ilce_id,
                        il_id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IlceKaydetAsync(string ilce_ad, int updated, int ilce_id, int il_id) {
            this.IlceKaydetAsync(ilce_ad, updated, ilce_id, il_id, null);
        }
        
        /// <remarks/>
        public void IlceKaydetAsync(string ilce_ad, int updated, int ilce_id, int il_id, object userState) {
            if ((this.IlceKaydetOperationCompleted == null)) {
                this.IlceKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIlceKaydetOperationCompleted);
            }
            this.InvokeAsync("IlceKaydet", new object[] {
                        ilce_ad,
                        updated,
                        ilce_id,
                        il_id}, this.IlceKaydetOperationCompleted, userState);
        }
        
        private void OnIlceKaydetOperationCompleted(object arg) {
            if ((this.IlceKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IlceKaydetCompleted(this, new IlceKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KanGruplariListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KanGruplariListesi() {
            object[] results = this.Invoke("KanGruplariListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KanGruplariListesiAsync() {
            this.KanGruplariListesiAsync(null);
        }
        
        /// <remarks/>
        public void KanGruplariListesiAsync(object userState) {
            if ((this.KanGruplariListesiOperationCompleted == null)) {
                this.KanGruplariListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKanGruplariListesiOperationCompleted);
            }
            this.InvokeAsync("KanGruplariListesi", new object[0], this.KanGruplariListesiOperationCompleted, userState);
        }
        
        private void OnKanGruplariListesiOperationCompleted(object arg) {
            if ((this.KanGruplariListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KanGruplariListesiCompleted(this, new KanGruplariListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KanGruplariKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KanGruplariKaydet(string adi, int id, int updated) {
            this.Invoke("KanGruplariKaydet", new object[] {
                        adi,
                        id,
                        updated});
        }
        
        /// <remarks/>
        public void KanGruplariKaydetAsync(string adi, int id, int updated) {
            this.KanGruplariKaydetAsync(adi, id, updated, null);
        }
        
        /// <remarks/>
        public void KanGruplariKaydetAsync(string adi, int id, int updated, object userState) {
            if ((this.KanGruplariKaydetOperationCompleted == null)) {
                this.KanGruplariKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKanGruplariKaydetOperationCompleted);
            }
            this.InvokeAsync("KanGruplariKaydet", new object[] {
                        adi,
                        id,
                        updated}, this.KanGruplariKaydetOperationCompleted, userState);
        }
        
        private void OnKanGruplariKaydetOperationCompleted(object arg) {
            if ((this.KanGruplariKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KanGruplariKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KullaniciListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KullaniciListesi(string adsoyad, string email, int kullaniciid) {
            object[] results = this.Invoke("KullaniciListesi", new object[] {
                        adsoyad,
                        email,
                        kullaniciid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciListesiAsync(string adsoyad, string email, int kullaniciid) {
            this.KullaniciListesiAsync(adsoyad, email, kullaniciid, null);
        }
        
        /// <remarks/>
        public void KullaniciListesiAsync(string adsoyad, string email, int kullaniciid, object userState) {
            if ((this.KullaniciListesiOperationCompleted == null)) {
                this.KullaniciListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciListesiOperationCompleted);
            }
            this.InvokeAsync("KullaniciListesi", new object[] {
                        adsoyad,
                        email,
                        kullaniciid}, this.KullaniciListesiOperationCompleted, userState);
        }
        
        private void OnKullaniciListesiOperationCompleted(object arg) {
            if ((this.KullaniciListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciListesiCompleted(this, new KullaniciListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KullaniciKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("onay")]
        public bool KullaniciKaydet(int kullaniciid, string email, string sifre, int durumid, string adisoyadi, string il, string ilce, string cinsiyet, System.DateTime dogumtarihi, string aciklama, int updated, int rolid, int ustkullaniciid, int kaydedenkullanici, out string aciklama1) {
            object[] results = this.Invoke("KullaniciKaydet", new object[] {
                        kullaniciid,
                        email,
                        sifre,
                        durumid,
                        adisoyadi,
                        il,
                        ilce,
                        cinsiyet,
                        dogumtarihi,
                        aciklama,
                        updated,
                        rolid,
                        ustkullaniciid,
                        kaydedenkullanici});
            aciklama1 = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciKaydetAsync(int kullaniciid, string email, string sifre, int durumid, string adisoyadi, string il, string ilce, string cinsiyet, System.DateTime dogumtarihi, string aciklama, int updated, int rolid, int ustkullaniciid, int kaydedenkullanici) {
            this.KullaniciKaydetAsync(kullaniciid, email, sifre, durumid, adisoyadi, il, ilce, cinsiyet, dogumtarihi, aciklama, updated, rolid, ustkullaniciid, kaydedenkullanici, null);
        }
        
        /// <remarks/>
        public void KullaniciKaydetAsync(int kullaniciid, string email, string sifre, int durumid, string adisoyadi, string il, string ilce, string cinsiyet, System.DateTime dogumtarihi, string aciklama, int updated, int rolid, int ustkullaniciid, int kaydedenkullanici, object userState) {
            if ((this.KullaniciKaydetOperationCompleted == null)) {
                this.KullaniciKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciKaydetOperationCompleted);
            }
            this.InvokeAsync("KullaniciKaydet", new object[] {
                        kullaniciid,
                        email,
                        sifre,
                        durumid,
                        adisoyadi,
                        il,
                        ilce,
                        cinsiyet,
                        dogumtarihi,
                        aciklama,
                        updated,
                        rolid,
                        ustkullaniciid,
                        kaydedenkullanici}, this.KullaniciKaydetOperationCompleted, userState);
        }
        
        private void OnKullaniciKaydetOperationCompleted(object arg) {
            if ((this.KullaniciKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciKaydetCompleted(this, new KullaniciKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RolListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RolListesi(int Kullaniciid) {
            object[] results = this.Invoke("RolListesi", new object[] {
                        Kullaniciid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RolListesiAsync(int Kullaniciid) {
            this.RolListesiAsync(Kullaniciid, null);
        }
        
        /// <remarks/>
        public void RolListesiAsync(int Kullaniciid, object userState) {
            if ((this.RolListesiOperationCompleted == null)) {
                this.RolListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRolListesiOperationCompleted);
            }
            this.InvokeAsync("RolListesi", new object[] {
                        Kullaniciid}, this.RolListesiOperationCompleted, userState);
        }
        
        private void OnRolListesiOperationCompleted(object arg) {
            if ((this.RolListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RolListesiCompleted(this, new RolListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KisiListesi(string adsoyad, string email, int kullaniciid) {
            object[] results = this.Invoke("KisiListesi", new object[] {
                        adsoyad,
                        email,
                        kullaniciid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KisiListesiAsync(string adsoyad, string email, int kullaniciid) {
            this.KisiListesiAsync(adsoyad, email, kullaniciid, null);
        }
        
        /// <remarks/>
        public void KisiListesiAsync(string adsoyad, string email, int kullaniciid, object userState) {
            if ((this.KisiListesiOperationCompleted == null)) {
                this.KisiListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiListesiOperationCompleted);
            }
            this.InvokeAsync("KisiListesi", new object[] {
                        adsoyad,
                        email,
                        kullaniciid}, this.KisiListesiOperationCompleted, userState);
        }
        
        private void OnKisiListesiOperationCompleted(object arg) {
            if ((this.KisiListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiListesiCompleted(this, new KisiListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UstKullaniciListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UstKullaniciListesi() {
            object[] results = this.Invoke("UstKullaniciListesi", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UstKullaniciListesiAsync() {
            this.UstKullaniciListesiAsync(null);
        }
        
        /// <remarks/>
        public void UstKullaniciListesiAsync(object userState) {
            if ((this.UstKullaniciListesiOperationCompleted == null)) {
                this.UstKullaniciListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUstKullaniciListesiOperationCompleted);
            }
            this.InvokeAsync("UstKullaniciListesi", new object[0], this.UstKullaniciListesiOperationCompleted, userState);
        }
        
        private void OnUstKullaniciListesiOperationCompleted(object arg) {
            if ((this.UstKullaniciListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UstKullaniciListesiCompleted(this, new UstKullaniciListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiKaydet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KisiKaydet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> kisiid, string email, string medenidurum, string unvan, bool iletisimizni, int kullaniciid, int kangrupid, bool aktif, string adisoyadi, string cinsiyet, System.DateTime dogumtarihi, string sirket, int updated, Telefonlar[] telefonlar, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fotograf) {
            this.Invoke("KisiKaydet", new object[] {
                        kisiid,
                        email,
                        medenidurum,
                        unvan,
                        iletisimizni,
                        kullaniciid,
                        kangrupid,
                        aktif,
                        adisoyadi,
                        cinsiyet,
                        dogumtarihi,
                        sirket,
                        updated,
                        telefonlar,
                        fotograf});
        }
        
        /// <remarks/>
        public void KisiKaydetAsync(System.Nullable<int> kisiid, string email, string medenidurum, string unvan, bool iletisimizni, int kullaniciid, int kangrupid, bool aktif, string adisoyadi, string cinsiyet, System.DateTime dogumtarihi, string sirket, int updated, Telefonlar[] telefonlar, byte[] fotograf) {
            this.KisiKaydetAsync(kisiid, email, medenidurum, unvan, iletisimizni, kullaniciid, kangrupid, aktif, adisoyadi, cinsiyet, dogumtarihi, sirket, updated, telefonlar, fotograf, null);
        }
        
        /// <remarks/>
        public void KisiKaydetAsync(
                    System.Nullable<int> kisiid, 
                    string email, 
                    string medenidurum, 
                    string unvan, 
                    bool iletisimizni, 
                    int kullaniciid, 
                    int kangrupid, 
                    bool aktif, 
                    string adisoyadi, 
                    string cinsiyet, 
                    System.DateTime dogumtarihi, 
                    string sirket, 
                    int updated, 
                    Telefonlar[] telefonlar, 
                    byte[] fotograf, 
                    object userState) {
            if ((this.KisiKaydetOperationCompleted == null)) {
                this.KisiKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiKaydetOperationCompleted);
            }
            this.InvokeAsync("KisiKaydet", new object[] {
                        kisiid,
                        email,
                        medenidurum,
                        unvan,
                        iletisimizni,
                        kullaniciid,
                        kangrupid,
                        aktif,
                        adisoyadi,
                        cinsiyet,
                        dogumtarihi,
                        sirket,
                        updated,
                        telefonlar,
                        fotograf}, this.KisiKaydetOperationCompleted, userState);
        }
        
        private void OnKisiKaydetOperationCompleted(object arg) {
            if ((this.KisiKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiKaydetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiTelefonlariGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KisiTelefonlariGetir(int kisi_id) {
            object[] results = this.Invoke("KisiTelefonlariGetir", new object[] {
                        kisi_id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KisiTelefonlariGetirAsync(int kisi_id) {
            this.KisiTelefonlariGetirAsync(kisi_id, null);
        }
        
        /// <remarks/>
        public void KisiTelefonlariGetirAsync(int kisi_id, object userState) {
            if ((this.KisiTelefonlariGetirOperationCompleted == null)) {
                this.KisiTelefonlariGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiTelefonlariGetirOperationCompleted);
            }
            this.InvokeAsync("KisiTelefonlariGetir", new object[] {
                        kisi_id}, this.KisiTelefonlariGetirOperationCompleted, userState);
        }
        
        private void OnKisiTelefonlariGetirOperationCompleted(object arg) {
            if ((this.KisiTelefonlariGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiTelefonlariGetirCompleted(this, new KisiTelefonlariGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Telefonlar {
        
        private int telefonIdField;
        
        private string telefonNoField;
        
        private int telefonTipiIdField;
        
        private int kullaniciIdField;
        
        private int kisiIdField;
        
        /// <remarks/>
        public int TelefonId {
            get {
                return this.telefonIdField;
            }
            set {
                this.telefonIdField = value;
            }
        }
        
        /// <remarks/>
        public string TelefonNo {
            get {
                return this.telefonNoField;
            }
            set {
                this.telefonNoField = value;
            }
        }
        
        /// <remarks/>
        public int TelefonTipiId {
            get {
                return this.telefonTipiIdField;
            }
            set {
                this.telefonTipiIdField = value;
            }
        }
        
        /// <remarks/>
        public int KullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                this.kullaniciIdField = value;
            }
        }
        
        /// <remarks/>
        public int KisiId {
            get {
                return this.kisiIdField;
            }
            set {
                this.kisiIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GirisKontrolCompletedEventHandler(object sender, GirisKontrolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GirisKontrolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GirisKontrolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string aciklama {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int kullanici_id {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int rol_id {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public int ustkullaniciid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string adsoyad {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DuzenleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IlListesiCompletedEventHandler(object sender, IlListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KullaniciDurumListesiCompletedEventHandler(object sender, KullaniciDurumListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciDurumListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciDurumListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KullaniciDurumuKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AdresTipiListesiCompletedEventHandler(object sender, AdresTipiListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdresTipiListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdresTipiListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AdresTipiKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IlKaydetCompletedEventHandler(object sender, IlKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TelefonListesiCompletedEventHandler(object sender, TelefonListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TelefonListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TelefonListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TelefonKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TelefonTipiListesiCompletedEventHandler(object sender, TelefonTipiListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TelefonTipiListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TelefonTipiListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TelefonTipiKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IlceListesiCompletedEventHandler(object sender, IlceListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlceListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlceListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void IlceKaydetCompletedEventHandler(object sender, IlceKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IlceKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IlceKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KanGruplariListesiCompletedEventHandler(object sender, KanGruplariListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KanGruplariListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KanGruplariListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KanGruplariKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KullaniciListesiCompletedEventHandler(object sender, KullaniciListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KullaniciKaydetCompletedEventHandler(object sender, KullaniciKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string aciklama1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RolListesiCompletedEventHandler(object sender, RolListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RolListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RolListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KisiListesiCompletedEventHandler(object sender, KisiListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UstKullaniciListesiCompletedEventHandler(object sender, UstKullaniciListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UstKullaniciListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UstKullaniciListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KisiKaydetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KisiTelefonlariGetirCompletedEventHandler(object sender, KisiTelefonlariGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiTelefonlariGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiTelefonlariGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591